[build]
  command = "rm -rf node_modules && npm cache clean --force && npm install && npm run build"
  publish = ".next"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"