[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment variables (for reference - set these in Netlify UI)
# OPENAI_API_KEY = "your-key"
# NEXT_PUBLIC_SITE_URL = "https://thenexus-ai.netlify.app"
# NODE_ENV = "production"