[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase function timeout to 26 seconds for CV parsing
  # (Netlify Free tier supports up to 26s)
  directory = ".netlify/functions/"
  included_files = ["**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Specific timeout for CV parsing endpoint
[[functions."parse-cv"]]
  timeout = 26